### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by felix91gr** [petrmanek/Revolver#2]
Hi. Your project looks interesting, but is it still being maintained? I ask because it would be cool to add it to [our index of swift cross-platform libraries](https://github.com/felix91gr/awesome-system-swift/) :3

**Comment by petrmanek** [comment]
Hello there! I originally worked on Revolver for my bachelor thesis and maintain it every now and then.

I would appreciate if more people got to know about it and possibly got involved!

P.
